### PR TITLE
Removed old south migrations and created new django migrations.

### PR DESCRIPTION
**Pull request by woutdp**
https://vikingco.atlassian.net/browse/MVBE-7074

This one should go after https://github.com/vikingco/django-experiments/pull/5

### CODE REVIEW

**Comment by jnsvr** [comment]
I don't see any 'Please review' label.

**Comment by pieterdd** [comment]
How did you generate this migration?

**Comment by woutdp** [comment]
@pieterdd I ran makemigrations.

**Comment by pieterdd** [comment]
Production will think it needs to run the initial migration again, so you'll need to perform a trick like the one described in https://github.com/vikingco/provider_kbc/pull/64#issuecomment-199349946.

**Comment by woutdp** [comment]
I will investigate if this is needed and make the necessary changes

**Comment by woutdp** [comment]
Could you review this again?
Explanation of what is going on is in the comments in the ticket. https://vikingco.atlassian.net/browse/MVBE-7074

**Comment by pieterdd** [comment]
:ship:

**Comment by pieterdd** [comment]
You will need an mvne-platform pull request when you're ready to release the non-empty migration though. Leaving in WIP for now.

**Comment by woutdp** [comment]
What do you mean Pieter? I have a pull request for the requirements in mvne-platform, is there another you think I need?

**Comment by pieterdd** [comment]
I clarified in person: you need one mvne PR for the empty migration and one for the filled-in migration.

**Comment by woutdp** [comment]
I created the one for empty migrations here: 
https://github.com/vikingco/mvne-platform/pull/5049

**Comment by WimCrols** [comment]
Since this is all generated, let's :shipit:

**Comment by linseyray** [comment]
:shipit:!

**Pull request merged**
